apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: finshare-prod
resources:
  - namespace.yaml
  - ../../base
patches:
  - target:
      kind: Deployment
      name: finshare-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
images:
  - name: ghcr.io/ajiths72/share-transfer-fintech
    newName: ghcr.io/ajiths72/share-transfer-fintech
    newTag: sha-cf67e664fd3295d11940fc345a329d1d412eb493
