apiVersion: v1
kind: Secret
metadata:
  name: finshare-secrets
  namespace: finshare-prod
type: Opaque
stringData:
  APP_SECRET: "replace-prod-secret"
  DATABASE_URL: "postgresql://finshare:change-me@postgres.finshare-prod.svc.cluster.local:5432/finshare"
