apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: finshare-dev
resources:
  - namespace.yaml
  - ../../base
patches:
  - target:
      kind: Deployment
      name: finshare-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
images:
  - name: ghcr.io/placeholder/finshare-transfer
    newName: ghcr.io/ajiths72/share-transfer-fintech
    newTag: sha-9a9e9a7f04aac73460fec793bf0066378cf7d643
