apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: finshare-dev
resources:
  - namespace.yaml
  - ../../base
patches:
  - target:
      kind: Deployment
      name: finshare-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
images:
  - name: ghcr.io/placeholder/finshare-transfer
    newName: ghcr.io/ajiths72/share-transfer-fintech
    newTag: sha-1639745efd975306234bbe53efdb72439ecd56eb
