apiVersion: v1
kind: Service
metadata:
  name: finshare-api
  labels:
    app: finshare-api
spec:
  selector:
    app: finshare-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
