apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finshare
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_OWNER/REPLACE_REPO.git
    targetRevision: main
    path: deploy/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: finshare
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
